public class Main {
    public static void main(String[] args) {
        task1();
    }

    public static void task1() {
        System.out.println("Задача 1");
         int a = 4000;
          System.out.println("Значение переменной а с типом int равно " + a);
         byte b = 122;
          System.out.println("Значение переменной b с типом byte равно " + b);
         short bi = 15236;
          System.out.println("Значение переменной bi с типом short равно " + bi);
         long d = 10237586;
          System.out.println("Значение переменной d с типом long равно " + d);
         float e = -5.75f;
          System.out.println("Значение переменной d с типом float равно " + e);
         double v = 5.75;
          System.out.println("Значение переменной v с типом double onравно " + v);
        System.out.println("Задача 2");
         float plot = 27.12f;
         long  brit = 987678965549L;
         double port = 2.786;
         int dark = 569;
         short red = -159;
         int rock =  27897;
         byte tip = 67;
        System.out.println("Задача 3");
         byte LP = 27;
         byte AS = 27;
         byte EA = 30;
         int paper = 480;
         int lernen = paper / (LP + AS + AS);
          System.out.println("На каждого ученика рассчитано " + lernen + " листов бумаги");
        System.out.println("Задача 4");
         int glass = 16 / 2;
         int time1 = 20;
         int time2 = 24 * 60;
         int time3 = (24 * 60) * 3;
         int time4  = (24 * 60) * 30;
         int glTi1 = glass * time1;
          System.out.println("За 20 мин. машина произвела " + glTi1 + " штук бутылок");
         int glTi2 = glass * time2;
          System.out.println("За сутки машина произвела " + glTi2 + " штук бутылок");
         int glTi3 = glass * time3;
          System.out.println("За 3 дня машина произвела " + glTi3 + " штук бутылок");
         int glTi4 = glass * time4;
          System.out.println("За месяц машина произвела " + glTi4 + " штук бутылок");
        System.out.println("Задача 5");
         byte paint = 120;
         byte white = 2;
         byte brown = 4;
         int clas = paint / (white + brown);
         int clasPaint1 = clas * white;
         int clasPaint2 = clas * brown;
          System.out.println("В школе, где " + clas + " классов, нужно " + clasPaint1+ " банок белой краски и " + clasPaint2 + " банок коричневой краски.");
        System.out.println("Задача 6");
         int banana = 5;
         int weightBanana = 80;
         int milk = 200 / 100;
         int weightMilk = 105;
         int ice = 2;
         int weighIce = 100;
         int egg = 4;
         int weighEgg = 70;
         int allWeighGr = (banana * weightBanana) + (milk * weightMilk) + (ice * weighIce) + (egg * weighEgg);
         int grPerKg = 1000;
         float allWeighKg = allWeighGr / (float)grPerKg;
          System.out.println("Завтрак в граммах получился равным " + allWeighGr);
          System.out.println("Завтрак в килограммах получился равным " + allWeighKg);
        System.out.println("Задача 7");
        int totalWeigh = 7;
        int wieghOne = 250;
        int wighTwo = 500;
        float deysOne = totalWeigh * grPerKg / wieghOne;
        System.out.println("Если сбрасывать по 250 грамм в день то понадобится " + deysOne + " дней");
        float deysTwo  = totalWeigh * grPerKg / wighTwo;
        System.out.println("Если сбрасывать по 500 грамм в день то понадобится " + deysTwo + " дней");
        float deys = (deysOne + deysTwo) / 2;
        System.out.println("В среднем понадобится " + deys + " день");
        System.out.println("Задача 8");
         int masha = 67760;
         int denis = 83690;
         int kristina = 76230;
         float pov = 1.1f;
         float mashaPov = masha * pov;
         float denisPov = denis * pov;
         float kristinaPov = kristina * pov;
         float year = 12;
         float mRaz = (mashaPov * year) - (masha *year);
         float dRaz = (denisPov * year) - (denis *year);
         float kRaz = (kristinaPov * year) - (kristina *year);
          System.out.println("Маша теперь получает " + mashaPov + " рублей. Годовой доход вырос на " + mRaz);
          System.out.println("Денис теперь получает " + denisPov + " рублей. Годовой доход вырос на " + dRaz);
          System.out.println("Кристина теперь получает " + kristinaPov + " рублей. Годовой доход вырос на " + kRaz);
    }
}